apiVersion: apps/v1
kind: Deployment
metadata: 
  name: weather2-app-deployment
  annotations: 
    kubernetes.io/change-cause: "Initial deployment of the app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather2-app
  template:
    metadata:
      name: myweather2k8s
      labels:
        env: prod
        app: weather2-app
        name: weather2-app
    spec:
      containers:
        - name: weather2-app
          image: chicone81/weather2-k8s:v3
          #imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http-web-api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80