# using LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: weather2-lb-service
spec: 
  selector:
      name: weather2-app
  ports:
    - name: weather2-app-port
      protocol: TCP
      port: 8081
      targetPort: 80
  type: LoadBalancer

# using NodePort
#apiVersion: v1
#kind: Service
#metadata:
#  name: weather2-service
#spec: 
#  selector:
#      app: weather-app
#  ports:
#    - name: weather-app-port
#      port: 8180
#      targetPort: 80
#  type: NodePort